require("jacob.plugins-setup") -- should be at the top 配置nvim所需要调用的文件指定
require("jacob.core.options")
require("jacob.core.keymaps")
require("jacob.core.colorscheme")
require("jacob.plugins.comment")
require("jacob.plugins.nvim-tree")
require("jacob.plugins.lualine")
require("jacob.plugins.telescope")
require("jacob.plugins.autopairs")
require("jacob.plugins.gitsigns")
require("jacob.plugins.treesitter")
require("jacob.plugins.nvim-cmp")
require("jacob.plugins.lsp.mason")
require("jacob.plugins.lsp.lspsaga")
require("jacob.plugins.lsp.lspconfig")
require("jacob.plugins.lsp.null-ls")
